# Welcome to Jekyll!
#

# Site settings
title: Foundational Web Hosting
description: |
  Providing the cornerstone of your digital infrastructure: premium, fully-managed 
  web hosting designed for resilience and blazing speed. We handle the technical 
  heavy lifting so you can focus on scaling your business.
owner: Foundational Web Hosting # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: jacob@foundationalwebhosting.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://foundationalwebhosting.com" # the base hostname & protocol for your site
social:
  linkedin-square: https://www.linkedin.com/company/foundationalwebhosting/
  youtube-square: https://www.youtube.com/@FoundationalWebHosting

# Build settings
markdown: kramdown
#sass:
#  style: compressed